### ISSUE TITLE
Export to draw.io is unsuccessful

### ISSUE THREAD

**Issue by citylineclark** [aws-solutions/workload-discovery-on-aws#329]
**Describe the bug**
When export to draw.io, an error comes up
n unsupported operand type(s) for *: 'NoneType' and 'float'

**To Reproduce**

1. Go to [Workload Discovery on AWS] > Diagrams > diagram > Export
2. select Diagrams.net (formerly Draw.io)
3. Export button is disabled
4. After a while, error comes up
unsupported operand type(s) for *: 'NoneType' and 'float'

**Expected behavior**
Export to draw.io should be successful. CSV export is successful. 

**Browser (please complete the following information):**

Tried on Chrome and Edge

**Additional context**

Checking the logs in cloudwatch [/aws/lambda/aws-perspective-DrawIoExportResolve-DrawIoFunction] this can be seen
[ERROR] TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/var/task/main.py", line 176, in handler
    xml_output = produce_xml_output(elements)
  File "/var/task/main.py", line 207, in produce_xml_output
    xml_object = elem.get_xml_object()
  File "/var/task/main.py", line 98, in get_xml_object
    'x': str(self.x),
  File "/var/task/main.py", line 67, in x
    children_points = list(
  File "/var/task/main.py", line 68, in <lambda>
    filter(None, map(lambda c: (c.center_x - 0.5*c.width), self.children)))
  File "/var/task/main.py", line 54, in width
    children_points = list(
  File "/var/task/main.py", line 55, in <lambda>
    filter(None, map(lambda c: (c.width*0.5 + c.center_x), self.children)))
  File "/var/task/main.py", line 54, in width
    children_points = list(
  File "/var/task/main.py", line 55, in <lambda>
    filter(None, map(lambda c: (c.width*0.5 + c.center_x), self.children)))

**Error on JSON Export**

Also see an error with JSON export, browser showing javascript error

CreateJSONExport.js:2 Uncaught TypeError: e.nodes is not a function
    at CreateJSONExport.js:2:24
    at onClick (ExportDiagram.js:50:18)

**Comment by svozza** [comment]
Can you try and rexport the diagram with your dev tools open and try to find the payload that's being sent to the `exportToDrawIo` GraphQL query? You'll find it in the network tab. Make sure to have dev tools open early, the library used on the frontend does pre-fetching so it's possible to miss the call. When you get the payload, attach it here so I can debug.

**Comment by citylineclark** [comment]
Dear Stefano

Please refer to the screenshot. I've also attached the HAR file.

The export button is diabled.

[cid:19d762c6-ba4a-481a-b46b-743557499a4d]
________________________________

**Comment by svozza** [comment]
I can't see any screenshot or file?

**Comment by citylineclark** [comment]
![image](https://user-images.githubusercontent.com/115068847/204782174-be5b2b39-fb28-41cb-a2aa-9fd3d8b82b70.png)

**Comment by citylineclark** [comment]
[d3ur63zqrnquq3.cloudfront.net.har.zip](https://github.com/awslabs/workload-discovery-on-aws/files/10122597/d3ur63zqrnquq3.cloudfront.net.har.zip)

**Comment by citylineclark** [comment]
Here are some errors in the HAR file

{"data":{"exportToDrawIo":null},"errors":[{"path":["exportToDrawIo"],"data":null,"errorType":"TypeError","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"unsupported operand type(s) for *: 'NoneType' and 'float'"}]}

{"data":{"getResourcesMetadata":null},"errors":[{"path":["getResourcesMetadata"],"data":null,"errorType":"Unhandled","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"2022-11-30T11:02:20.037Z d23f8332-2cbd-44f4-b520-27f690b82b0e Task timed out after 15.02 seconds"}]}

**Comment by jwesley235** [comment]
Same issue on Safari and Chrome on MacOS. I can export a diagram with no filters, but once I remove too many items, it starts throwing this error.

**Comment by dprzysiecki** [comment]
I'm also having this issue. Anyone knows if the export to diagrams.net worked in any of the previous versions? The issue was reported not long ago I could assume the export has worked in older version. I haven't used this tool before just yesterday started and encountered this issue.

**Comment by CarterSheehan** [comment]
I just deployed this solution into a fresh AWS account on Tuesday and am having the same issue when trying to export into a draw.io compatible format

**Comment by CarterSheehan** [comment]
I went down the path of trying to get more info printed out within the DrawIo lambda function when I had a idea that maybe something with the diagram itself was bad or not being sent to the function properly that I cleared the diagram and added a VPC resource and tried to export again, which worked. So, it feels like it could have something to do with the client-side request.

**Comment by eliasbedmar** [comment]
I'm also having this issue.

**Comment by mresetar-croz** [comment]
I've deployed  v2.10 and I'm having this issue. 
Response from graphql:

`{
    "data": {
        "exportToDrawIo": ""
    },
    "errors": [
        {
            "path": [
                "exportToDrawIo"
            ],
            "data": null,
            "errorType": "Lambda:Unhandled",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "unsupported operand type(s) for *: 'NoneType' and 'float'"
        }
    ]
}`

**Comment by svozza** [comment]
It looks like the v2.1.0 release only partially fixed the issue, we will track in https://github.com/aws-solutions/workload-discovery-on-aws/issues/458.
